### ISSUE TITLE
Problem when autenticating

### ISSUE THREAD

**Issue by lupohirp** [kayrus/gof5#11]
Hi,

i have this problem when i'm doing the authentication : 

failed to login: Get "https:": http: no Host in request URL

i'm using the --select parameter

Any idea to how to solve it?

**Comment by kayrus** [comment]
@lupohirp which server do you use and what do you select in "select" menu?

**Comment by lupohirp** [comment]
I'm trying to connect to this server : https://vpn.it.nttdata-emea.com/my.policy

It requires web logon.

**Comment by kayrus** [comment]
Issue was fixed in v0.0.7
