### ISSUE TITLE
fatal read tun: read /dev/net/tun: not pollable

### ISSUE THREAD

**Issue by lupohirp** [kayrus/gof5#13]
Hi,

with the latest version i'm connecting succesfully. 
But it stops immediately because of this error : fatal read tun: read /dev/net/tun: not pollable

**Comment by kayrus** [comment]
@lupohirp please answer questions below:
* do you use sudo?
* does it work with an older version? which one?
* which OS do you use?
* what is the output of `ifconfig`?
* does it work after reboot?

**Comment by lupohirp** [comment]
Hi : 

- do you use sudo? yes 
- does it work with an older version? which one? nope. my VPN is 2FA, so the latest version is the one that works correctly. Infact i'm connecting succesfully
-  which OS do you use? Chrome OS
-  what is the output of ifconfig? arc_wlan0: flags=4675<UP,BROADCAST,RUNNING,ALLMULTI,MULTICAST>  mtu 1500
        inet 100.115.92.13  netmask 255.255.255.252  broadcast 100.115.92.15
        inet6 fe80::1855:6fff:fefd:1d49  prefixlen 64  scopeid 0x20<link>
        ether 96:a0:fe:d5:c2:76  txqueuelen 1000  (Ethernet)
        RX packets 2282  bytes 550500 (537.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8820  bytes 2121370 (2.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

arcbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 100.115.92.1  netmask 255.255.255.252  broadcast 100.115.92.3
        inet6 fe80::3884:46ff:fe02:6934  prefixlen 64  scopeid 0x20<link>
        ether be:d6:c8:85:32:4b  txqueuelen 1000  (Ethernet)
        RX packets 15  bytes 916 (916.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 286  bytes 27482 (26.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1775  bytes 132728 (129.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1775  bytes 132728 (129.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vetharc0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::bcd6:c8ff:fe85:324b  prefixlen 64  scopeid 0x20<link>
        ether be:d6:c8:85:32:4b  txqueuelen 1000  (Ethernet)
        RX packets 16  bytes 1216 (1.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 291  bytes 28064 (27.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethwlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::94a0:feff:fed5:c276  prefixlen 64  scopeid 0x20<link>
        ether 96:a0:fe:d5:c2:76  txqueuelen 1000  (Ethernet)
        RX packets 2283  bytes 582538 (568.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8825  bytes 2121952 (2.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vmtap0: flags=4675<UP,BROADCAST,RUNNING,ALLMULTI,MULTICAST>  mtu 1500
        inet 100.115.92.25  netmask 255.255.255.252  broadcast 100.115.92.27
        inet6 fe80::e40d:21ff:feeb:10b6  prefixlen 64  scopeid 0x20<link>
        ether e6:0d:21:eb:10:b6  txqueuelen 1000  (Ethernet)
        RX packets 97360  bytes 22322063 (21.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 130389  bytes 462541250 (441.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4675<UP,BROADCAST,RUNNING,ALLMULTI,MULTICAST>  mtu 1500
        inet 192.168.1.6  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::3e6a:a7ff:fe27:99a8  prefixlen 64  scopeid 0x20<link>
        ether 3c:6a:a7:27:99:a8  txqueuelen 1000  (Ethernet)
        RX packets 722231  bytes 990376381 (944.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 197428  bytes 30216513 (28.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

- does it work after reboot? nope

**Comment by kayrus** [comment]
@lupohirp I reproduced an issue in chromeos. As a workaround try to use `driver: pppd` in `~/.gof5/config.yaml`.

**Comment by lupohirp** [comment]
Ok connected succesfully. But it doesn't resolve with VPN DNS. If i try to ping a host behind the VPN, it doesn't work.

**Comment by kayrus** [comment]
@lupohirp you need to specify corporate network routes in `~/.gof5/config`.

Another workaround for the `not pollable` error is to restart shill:

```
sudo stop shill
sudo start shill BLACKLISTED_DEVICES=tun0
```

**Comment by lupohirp** [comment]
in routes property?

**Comment by kayrus** [comment]
@lupohirp yes

**Comment by lupohirp** [comment]
I have specified, but now for example Internet is already gone and it can't reach.

**Comment by kayrus** [comment]
@lupohirp what do you mean?

**Comment by lupohirp** [comment]
i mean that i can't reach even google for example....but i should....i'm not experienced in networkink so maybe i'm doing something wrong

**Comment by kayrus** [comment]
@lupohirp gof5 doesn't fetch routes from the F5 server yet, you have to specify routes manually in `~/.gof5/config.yaml`.

**Comment by lupohirp** [comment]
mmm i have specified the routes ( i've taken from windows version of Big IP Edge ) but unrfotunately it doesn't work. Maybe ( rather.....for sure :) i've setted something wrong or maybe i'm missing something. I will wait version fetch routes automatically. Tnx kayrus for this work. It's really great. It should be by the company, but it seems that linux it doesn't exist....

**Comment by kayrus** [comment]
@lupohirp F5 has a Linux VPN client, but it is not opensource and its behavior cannot be customized.
Have you managed to fix routes at the end? Have you tried to specify a `0.0.0.0/0` route for instance?

**Comment by kayrus** [comment]
@lupohirp support for routes, pushed by F5, was added in the recent release

**Comment by kayrus** [comment]
Support for ChromeOS with special config options was added. See https://github.com/kayrus/gof5#chromeos for details

**Comment by kayrus** [comment]
@lupohirp for chromos 85 and greater use `sudo restart shill BLOCKED_DEVICES=tun0` to unblacklist the tun0 device.
