### ISSUE TITLE
Hostname lookup doesn't work with multiple entries

### ISSUE THREAD

**Issue by ybaldus** [kayrus/gof5#14]
At the moment the search entry inside /etc/resolv.conf is comma separated:

`
search domain1,domain2,domain3,domain4
`

 According to the spec this should be space or tab separated:

`
search domain1 domain2 domain3 domain4
`

**Comment by kayrus** [comment]
@ybaldus fixed in https://github.com/kayrus/gof5/commit/20234e04c7bc7517178792155f1e9b5cd32fb85a

**Comment by ybaldus** [comment]
Works like a charm, thanks.
