### ISSUE TITLE
Arch Linux Package

### ISSUE THREAD

**Issue by alfredopalhares** [kayrus/gof5#19]
Hello,

I have created an Arch Linux Package for gof5.
Its in the [AUR](https://aur.archlinux.org/packages/gof5/) and I keep all the sources on my [public repository](https://github.com/alfredopalhares/arch-pkgbuilds) you might want to add this to your README, any feedback is welcome.

On Arch all you need is to use aur wrapper like yay and install it like such:
```
yay -S gof5
```

Thank you for this great tool.

**Comment by kayrus** [comment]
@alfredopalhares thanks for letting me know about the package. Please note that you must enable CGO, otherwise user detection may fail on systems, which use sssd or similar daemons with centralized user management.
Do you need anything from my side or can I close the issue?

**Comment by alfredopalhares** [comment]
@kayrus  how do I enable GCO ? Do you mean [this](https://golang.org/cmd/cgo/)

**Comment by kayrus** [comment]
@alfredopalhares yes. It is enabled by default in [Makefile](https://github.com/kayrus/gof5/blob/52fbc16019bf915d8ebad8d6da46d1b7f61761ce/Makefile#L9-L10)

**Comment by alfredopalhares** [comment]
I am using the Makefiel to build the application. the system works.
