### ISSUE TITLE
Failed to set upd/tcp listener (macOS)

### ISSUE THREAD

**Issue by christopherhans** [kayrus/gof5#2]
When trying to exceute the gof5_darwin it fails with:
````
2020/04/29 14:56:43 Setting /etc/resolv.conf
2020/04/29 14:56:43 Serving DNS proxy on 127.0.0.253:53
2020/04/29 14:56:43 Forwarding ["corp.int." "corp."] DNS requests to ["10.17.220.85" "10.4.12.193"]
2020/04/29 14:56:43 Failed to set udp listener listen udp 127.0.0.253:53: bind: can't assign requested address
2020/04/29 14:56:43 Failed to set tcp listener listen tcp 127.0.0.253:53: bind: can't assign requested address
````

Probably a mac related issue.

**Comment by kayrus** [comment]
@christopherhans can you disable dns by commenting it out?

**Comment by christopherhans** [comment]
results in `fatal read http: EOF`

**Comment by kayrus** [comment]
@christopherhans unfortunately I don't have an ability to provide a support for macos. I added a note in readme. You're welcome to submit a pull request. It appeared that there are at least two issues:
* netlink package doesn't support macos
* it is impossible to bound `127.0.0.253`

**Comment by kayrus** [comment]
@christopherhans I added macos support. At least VPN works in FreeBSD. You can try the latest master.

**Comment by kayrus** [comment]
a version with macos support has been released
