### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by 0anton** [kayrus/gof5#29]
I start getting an error today:
```
2021/02/28 15:31:25 gof5 version: v0.0.6
2021/02/28 15:31:25 Logging in...
2021/02/28 15:31:25 failed to login: Get "https://xxx": x509: certificate signed by unknown authority
```
Wondering if there is a way to disable certificate check, like an 'insecure' option for _curl -k_?

**Comment by kayrus** [comment]
see the latest [release](https://github.com/kayrus/gof5/releases/tag/v0.1.1), where you can define custom ca-cert. Also config file supports `insecureTLS: true`, but I strongly recommend to use it only for dev purposes.

**Comment by 0anton** [comment]
Thanks a lot @kayrus for fast and helpful answer. It is a great please to have your software and service to the community.
