### ISSUE TITLE
build fails with golang 1.13

### ISSUE THREAD

**Issue by renatopancheri** [kayrus/gof5#34]
Hi,

i'm a newbie with golang and when running make with `golang 1.13` (default on ubuntu 20.04) i get a pretty obscure message:
```
build io/fs: cannot load io/fs: open /home/renato/git_repo/gof5/vendor/io/fs: no such file or directory
```
maybe adding something on the readme or checking go version on makefile would be useful for not very skilled developers like me.

**Comment by kayrus** [comment]
FYI: I just tried to compile gof5 with go 1.13, but I noticed another issue:

```
go build kernel.org/pub/linux/libs/security/libcap/psx: invalid flag in #cgo LDFLAGS: -Wl,-wrap,pthread_create
```

I don't know what exactly causes this, thus I'd recommend you to download the latest go version.
