### ISSUE TITLE
Support TLS renegotatiation?

### ISSUE THREAD

**Issue by fenuks** [kayrus/gof5#40]
The VPN server I connect to requires renegotiation. gof5 fails with tls: no renegotiation.

I am not familiar with go, but I managed to find the solution on the internet

```diff
--- gof5-0.1.4/pkg/client/http.go       2021-10-29 13:19:18.000000000 +0200
+++ src/gof5-0.1.4/pkg/client/http.go   2022-02-02 11:27:31.593142532 +0100
@@ -35,6 +35,7 @@
 func tlsConfig(opts *Options, insecure bool) (*tls.Config, error) {
        config := &tls.Config{
                InsecureSkipVerify: insecure,
+               Renegotiation:      tls.RenegotiateOnceAsClient,
        }
 
        if opts.CACert != "" {
```
and it works for me. Is there any reason to not enable it by default for everybody?

**Comment by kayrus** [comment]
I'd rather add this option into the config. Can you prepare a PR?

**Comment by fenuks** [comment]
Alright, I will try to.
