### ISSUE TITLE
Support logging of DNS requests

### ISSUE THREAD

**Issue by watkit** [kayrus/gof5#41]
Is it possible to have a flag or config item that would enable the gof5 application to log the DNS requests/responses it processes without using the full debug logging?
Being able to view the domain name requested, the server that provided the response used, and the IP addresses provided in response by that server, would help a lot in debugging split routing settings.

**Comment by kayrus** [comment]
you can modify the source code accordingly:
```diff
diff --git a/pkg/dns/dns.go b/pkg/dns/dns.go
index 781b20c..1e2f2b9 100644
--- a/pkg/dns/dns.go
+++ b/pkg/dns/dns.go
@@ -58,7 +58,7 @@ func dnsHandler(w dns.ResponseWriter, m *dns.Msg, cfg *config.Config, proto stri
        c.Net = proto
        for _, suffix := range cfg.DNS {
                if strings.HasSuffix(m.Question[0].Name, suffix) {
-                       if cfg.Debug {
+                       if true || cfg.Debug {
                                log.Printf("Resolving %q using VPN DNS", m.Question[0].Name)
                        }
                        for _, s := range cfg.F5Config.Object.DNS {
```

Feel free to submit a PS with different levels of logging.

**Comment by watkit** [comment]
My hero, thanks!
I've never written anything in go before, but I'll see if I can't figure it out when I have some free time. Great app, appreciate your having made it, and your help. 😊
