### ISSUE TITLE
support two-factor authentication

### ISSUE THREAD

**Issue by smasher164** [kayrus/gof5#6]
Thank you for working on this project! This could bring me one step closer to automating my vpn. Currently we use the BIG-IP Edge Client, which additionally prompts for a one-time password. I have an authentication agent (rsc.io/2fa) that generates TOTP authentication codes, but I have no way to enter this information with gof5.

**Comment by kayrus** [comment]
@smasher164 you can enable the debug flag and see for patterns bigip server sends for a 2fa. Introducing a new pattern logic should be easy enough.

**Comment by smasher164** [comment]
> you can enable the debug flag and see for patterns bigip server sends for a 2fa.

Thanks! I'll look into this.

**Comment by smasher164** [comment]
It seems that the GET request to `/my.logon.php3?outform=xml&client_version=2.0&get_token=1` and the POST request to `/my.policy` are not being made, because the initial request to the vpn server goes through enough redirects that the Roundtripper prints `"Connection error, retries exhausted. Aborting"`. When I inspect the traffic from the GUI BIG-IP client, the first request is sent to `/my.logon.php3?outform=xml&client_version=2.0&get_token=1`. I'm going to try modifying the gof5 client to not separate the path from the server URL.

**Comment by kayrus** [comment]
@smasher164 can you share the debug output, when 2fa is requested by bigip?

**Comment by kayrus** [comment]
@smasher164 any news on this issue?

**Comment by smasher164** [comment]
@kayrus Sorry for being unresponsive. I have debug output, but some of that info needs to be redacted. Is there a separate way I can send you that info?

**Comment by kayrus** [comment]
@smasher164 you can create a secret gist and send me a link by email. email can be found in the git log.

**Comment by dlasher** [comment]
+1 to this request.

**Comment by kayrus** [comment]
It's quite problematic to support MFA, therefore a new `--session` CLI parameter was added. You can log in using browser, then obtain a session ID using `document.cookie.match(/MRHSession=(.*?); /)[1]` javascript in a browser developer console.
