### ISSUE TITLE
Feature req: don't change resolv.conf

### ISSUE THREAD

**Issue by 0anton** [kayrus/gof5#7]
Is it possible to add feature of not changing the resolv.conf?
My use-case: after the tunnel is expired / broken, it is not possible to establish the new one, because resolv.conf remains showing on 127.0.0.1, which is not responding anymore. Manuall re-creation is needed. I prefer to manage DNS configuration for tunnel in separate dnsmasq configuration:

	2020/07/15 09:35:57 failed to get VPN profiles: Get "https://xxx/vpn/index.php3?outform=xml&client_version=2.0": dial tcp: lookup xxxx on 127.0.0.1:53: read udp 127.0.0.1:35231->127.0.0.1:53: read: connection refused

**Comment by kayrus** [comment]
> after the tunnel is expired / broken, it is not possible to establish the new one, because resolv.conf remains showing on 127.0.0.1

@0anton, this should not happen, since there is a hook to restore the config on fail/crash. Can you show the log of the failure?

Here is what I see, when VPN tunnel breaks:

```
2020/07/15 09:19:02 Restoring original /etc/resolv.conf
2020/07/15 09:19:02 failed to delete 1.2.3.4 route from "tun0" interface: no such process
2020/07/15 09:19:02 failed to read F5 packet header: read tcp 192.168.1.13:37332->1.2.3.4:443: read: connection reset by peer
```

The hook restores the `/etc/resolv.conf`

**Comment by 0anton** [comment]
The hook didn't work after the process got SIGPIPE (closed ssh session), but the problem is not this. I simply want to avoid resolv.conf manipulation at all, since I set the right DNS somewhere else.

I suggest the following logic: in the absence of _listenDNS_ key in the _config.yaml_ don't start own resolver and don't manipulate _resolve.conf_. So user can choose if he wants this feature or not.

    listenDNS: 127.0.0.1

**Comment by kayrus** [comment]
@0anton I added SIGPIPE handling + `disableDNS` option in config file. A new release should be upoloaded by travis pipeline soon.
