### ISSUE TITLE
re-create route to tun0 interface if it is already exists

### ISSUE THREAD

**Issue by 0anton** [kayrus/gof5#8]
Is is possible to re-use or automatically remove/re-create route after broken tunnel to avoid manual intervention? The route remains created if gof5 process died e.g. because of sigpipe signal:

	2020/07/15 09:37:14 failed to add xxx.xx.xx.xx route to "tun0" interface: file exists

**Comment by kayrus** [comment]
This issue is similar to #5. However I'd prefer to add the same logic for all platforms, not only to Linux.

**Comment by 0anton** [comment]
Oh, I missed it. Sure, it is identical. The #5 has even specific recommendations how to deal with the already existing routes. Feel free to close the current.
