### ISSUE TITLE
Understand and properly log "session expired" condition

### ISSUE THREAD

**Issue by 0anton** [kayrus/gof5#9]
My VPN expires after 24 hours & closed connection. Gof5 can understand this situation and log it properly (there not much one can do to react on that). Current output:

```
2020/07/17 09:52:26 unknown PPP data:
00000000  ff 03 c0 21 05 03 00 13  53 65 73 73 69 6f 6e 20  |...!....Session |
00000010  65 78 70 69 72 65 64                              |expired|
```

**Comment by kayrus** [comment]
@0anton this is the server side limitation. Once session is established, it is valid for 24h. I'll try to add a proper handling for this behavior.

**Comment by kayrus** [comment]
Fixed in https://github.com/kayrus/gof5/commit/ee825a62fc0ee851bd08baa22c25bed78efabb52
@0anton feel free to introduce a proper ppp protocol logic. Currently it is written based on the traffic dump reverse engineering without any reference to RFC.

**Comment by 0anton** [comment]
Thanks a lot, @kayrus!
Sure, it is a server side configuration. I never meant gof5 does anything wrong here. I'd just thought that you and community can profit if gof5 properly recognizes this situation. Though for now I don't have any ideas, what client can go once the session is expired besides of logging in again (and supplying a proper password).
So far, all works perfect! Thanks for a wonderful tiny tool!
